### ISSUE TITLE
[Suggestion] Make mutiplier slider allow lower values

### ISSUE THREAD

**Issue by Rafii2198** [LizIsTired/cave_dust#4]
For me, there are too much of these particles, I would like it to be more of a nice ambience but currently it is a bit too intrusive.
So if the multiplayer slider allowed for smaller values than 1 then it would allow me to set it as nice ambience.

**Comment by LizIsTired** [comment]
Thanks for your suggestion!
This is a bit tricky, I was trying to navigate a fine line between too much and too little when hardcoding the default values and ended up multiplying the default value by 10 in order to create more, I can absolutely reduce that back down though! 
There was also the config situation, the slider wasn't nice to use when it let you do decimal values (floats), and also the way my code works will only work with whole numbers (integers) so I think the best way would be a combination of a refactor and to turn down that hardcoded default value haha

**Comment by Rafii2198** [comment]
How about instead of multiplying base value by 10, make the default multiplayer 10 so it would give the same effect by default while avoiding decimal values in the slider, if I understand correctly? If you would do it then the max value in the slider would also need to be 10 times bigger.

That way the mod would also look the same by default and would give a better options for people who would like to change it!

**Comment by LizIsTired** [comment]
Implemented!
